### ISSUE TITLE
I used it to cross-compile with rust and it compiled, but got an error.

### ISSUE THREAD

**Issue by kekeqy** [trcrsired/windows-hosted-x86_64-linux-gnu-gcc-cross-compiler#1]
[root@iZm5e88py6i3nrgdoevku9Z home]# ./boom
./boom: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./boom)
./boom: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./boom)
./boom: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./boom)

**Comment by trcrsired** [comment]
这个只支持ubuntu 22.04以上的

**Comment by kekeqy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
